version: "3.9"
services:
 frontend:
   build:
     context: ./frontend
     dockerfile: Dockerfile
   container_name: vite-turisztika
   restart: always
   ports:
     - 8100:8100
   volumes:
     - ./frontend:/app
     - /app/node_modules
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost/api
   networks:
     - network
networks:
 network: