# Generated by Django 5.1.4 on 2024-12-14 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orszag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orszagMegnevezes', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Országok',
            },
        ),
        migrations.CreateModel(
            name='Varos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varosMegnevezese', models.CharField(max_length=100)),
                ('orszag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.orszag')),
            ],
            options={
                'verbose_name_plural': 'Városok',
            },
        ),
        migrations.CreateModel(
            name='Latvanyossag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latvanyossagMegnevezes', models.CharField(max_length=100)),
                ('latvanyossagLeiras', models.TextField()),
                ('ertekeles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nyitvatartas', models.CharField(max_length=50)),
                ('kepUrl', models.CharField(max_length=100)),
                ('varos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.varos')),
            ],
            options={
                'verbose_name_plural': 'Látványosságok',
            },
        ),
    ]
