# Generated by Django 5.1.4 on 2024-12-22 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iranyitoszam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megnevezes', models.CharField(max_length=500)),
                ('irsz', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'verbose_name_plural': 'Irányítószám',
            },
        ),
        migrations.CreateModel(
            name='Orszag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orszagMegnevezes', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Túl rövid országnévnek. (min:4)'), django.core.validators.MaxLengthValidator(58, message='Túl hosszú országnévnek. (max: 85)')])),
            ],
            options={
                'verbose_name_plural': 'Országok',
            },
        ),
        migrations.CreateModel(
            name='Varos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varosMegnevezes', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Túl rövid városnévnek. (min:4)'), django.core.validators.MaxLengthValidator(85, message='Túl hosszú városnévnek. (max: 85)')])),
                ('orszag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.orszag')),
            ],
            options={
                'verbose_name_plural': 'Városok',
            },
        ),
        migrations.CreateModel(
            name='Latvanyossag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latvanyossagMegnevezes', models.CharField(max_length=500)),
                ('latvanyossagLeiras', models.TextField()),
                ('nyitvatartas', models.CharField(max_length=200)),
                ('kepUrl', models.CharField(max_length=500)),
                ('varos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.varos')),
            ],
            options={
                'verbose_name_plural': 'Látványosságok',
            },
        ),
        migrations.CreateModel(
            name='Ertekeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ertekeles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('velemeny', models.TextField()),
                ('pozitiv', models.TextField()),
                ('negativ', models.TextField()),
                ('ertekelo', models.CharField(max_length=100)),
                ('iranyitoszam', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('attrakcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.varos')),
            ],
            options={
                'verbose_name_plural': 'Értékelés',
            },
        ),
    ]
