# Generated by Django 5.1.4 on 2024-12-22 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turisztikailatvanyossagok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ertekeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ertekeles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('velemeny', models.TextField()),
                ('pozitiv', models.TextField()),
                ('negativ', models.TextField()),
                ('iranyitoszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.iranyitoszam')),
            ],
            options={
                'verbose_name_plural': 'Értékelés',
            },
        ),
    ]
