# Generated by Django 5.1.4 on 2024-12-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turisztikailatvanyossagok', '0002_ertekeles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ertekeles',
            name='varos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turisztikailatvanyossagok.varos'),
            preserve_default=False,
        ),
    ]
