# Generated by Django 5.1.4 on 2024-12-15 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turisztikailatvanyossagok', '0002_alter_latvanyossag_nyitvatartas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orszag',
            name='orszagMegnevezes',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Túl rövid országnévnek. (min:4)'), django.core.validators.MaxLengthValidator(58, message='Túl hosszú országnévnek. (max: 85)')]),
        ),
    ]
